# environment.yml
# This file defines the software environment for the nanopore analysis pipeline.
# It lists the dependencies for the pipeline to work properly.

name: nanopore_analysis

channels:
  # Conda will search these channels in this order when it tries to find a program
  - conda-forge
  - bioconda
  - nanoporetech
  - defaults
dependencies:
  - python=3.9
  - unzip
  - curl
  - pyarrow=20.0
  - go-yq
  - bedtools
  - pybedtools
  - requests
  - pandas
  - scipy
  - matplotlib
  - conda_forge:gxx
  - pysam
  - tqdm
  - pip
  - pip:
    - pyyaml
    #- pandas
    #- scipy
    #- matplotlib
    - colorlog
  # --- Conda Packages ---
  - minimap2
  - samtools
  - pod5
  - typing-extensions
  - modkit